# Generated by Django 5.2.4 on 2025-09-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=16)),
                ('cpassword', models.CharField(max_length=16)),
            ],
        ),
    ]
